name = "realizability"
version = "0.1.0"
defaultTargets = ["realizability"]

[[lean_lib]]
name = "Realizability"

[[lean_exe]]
name = "realizability"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0-rc1"
